name: Deploy Ski App Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: 'root'
          TARGET: '/root'
          EXCLUDE: '/node_modules/'
          SCRIPT_AFTER: |
            cd /root/project/skiboard_backend
            git pull
            pnpm install
            pnpm run build
            pm2 reload
